# Name of workflow
name: Lint workflow!

# Trigger the workflow on pull requests
on:
  pull_request:
    branches:
      - develop
      - staging
      - main

# Jobs to run
jobs:
  test:
    runs-on: ubuntu-latest

    # Steps to run in the job
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Use node.js 21.x
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 21.x

      - name: Install deps
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Run test
        run: npm run test